mysql: false
update-default-exp: true
#更新原版经验
disabled-default-exp-change: false
#禁止原版经验更改
default-exp:
  enable: true
  value: 1.0
level-sure-exp:
  - "5:500"
  - "10:1000"
  - "25:3000"
level-up-string-action:
  '5':
    - '成功升级至xxx'
    - '[TITLE]10;70;20; ;成功升级至xxx'
