name: SX-Level-Reload
main: github.saukiya.sxlevel.SXLevel
version: "${version}"
author: "Saukiya, WCPE"
softdepend:
  - MythicMobs
  - AttributePlus
depend: [ "WcpeLib" ]
commands:
  sxlevel:
    usage: error! please reload this plugin
    aliases:
      - sl

permissions:
  sx-level.use:
    default: true